### ISSUE TITLE
Include dataset

### ISSUE THREAD

**Issue by guillemcortes** [alexanderlerch/audiocontentanalysis.org#2]
Hi,

I'm opening a request to include _BAF: an audio fingerprinting dataset for broadcast monitoring_ to the list in https://www.audiocontentanalysis.org/datasets.html.

Links:
Zenodo (Dataset): https://zenodo.org/record/6868083
GitHub: https://github.com/guillemcortes/baf-dataset

Let me know if you need more information.

Thanks,

Guillem

**Comment by alexanderlerch** [comment]
thanks, added.

**Comment by guillemcortes** [comment]
(Just FYI) Later I thought that you might be serving the list from ismir/mir-datasets and created this PR there https://github.com/ismir/mir-datasets/pull/47
